services:
  virtuoso:
    image: tenforce/virtuoso
    ports:
      - "8890:8890"
      - "1111:1111"
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "https://rub-al-khali.bio2vec.net/consensus"
      VIRT_Parameters_NumberOfBuffers: 10000
      VIRT_Parameters_MaxDirtyBuffers: 6000
      # Explicitly allow access to the mounted /data directory and subdirectories
      VIRT_Parameters_DirsAllowed: "., /data"
    volumes:
      - ./project:/data